# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: django-tinymce4-plus
site_url: http://danfimov.gitlab.io/django-tinymce4-plus
repo_url: https://github.com/danfimov/django-tinymce4-plus
repo_name: django-tinymce4-plus

nav:
  - General: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Usage: usage.md
  - Advanced usage: advanced.md
  - Example project: example_project.md
  - Contributing:
      - contributing.md
  - Changelog: changelog.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
  icon:
    repo: fontawesome/brands/github-alt
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Use light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Use dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Use system colors

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  links:
    absolute_links: relative_to_docs

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - tables
  - attr_list
  - admonition
  - md_in_html  # for badges in readme.md

plugins:
  - search
