name: Run all tests
on: [pull_request]

jobs:
  test-basic:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
        django-version: ["django-1.11", "django-4.2"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-uv
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          uv pip install --system .[optionals,testing]
      - name: Install Dajngo 1.11
        if: matrix.django-version == 'django-1.11'
        run: uv pip install --system "django==1.11.29"
      - name: Install Django 4.2
        if: matrix.django-version == 'django-4.2'
        run: uv pip install --system "django==4.2.17"
      - run: mkdir coverage
      - name: Test
        run: >
          uv run pytest

