name: Check code quality
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint code
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - id: setup-uv
        uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v7.1.0
        with:
          enable-cache: true
          version: "latest"
          python-version: 3.12
      - name: Install Dependencies
        run: uv sync --all-extras
      - run: uv run ruff check . --output-format github

  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Test with pytest
    strategy:
      matrix:
        python-version: ["3.8", "3.11", "3.13"]
        django-version: ["django-1.11", "django-4.2"]
      fail-fast: false
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - id: setup-uv
        uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v7.1.0
        with:
          enable-cache: true
          cache-suffix: ${{ matrix.python-version }}
          version: "latest"
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: uv sync --all-extras
      - name: Install Dajngo 1.11
        if: matrix.django-version == 'django-1.11'
        run: uv pip install "django==1.11.29"
      - name: Install Django 4.2
        if: matrix.django-version == 'django-4.2'
        run: uv pip install "django==4.2.17"
      - name: Test
        run: uv run pytest
